Repository FindMeWithDeepDive/DangDangCrew, pull requests merged in 2025-02, with the labels that each got.

#7 [#3] 모임 도메인 추가
  build.gradle
  src/main/java/findme/dangdangcrew/meeting/controller/MeetingController.java
  src/main/java/findme/dangdangcrew/meeting/dto/MeetingRequestDto.java
  src/main/java/findme/dangdangcrew/meeting/dto/MeetingResponseDto.java
  src/main/java/findme/dangdangcrew/meeting/entity/Meeting.java
  src/main/java/findme/dangdangcrew/meeting/mapper/MeetingMapper.java
  src/main/java/findme/dangdangcrew/meeting/repository/MeetingRepository.java
  src/main/java/findme/dangdangcrew/meeting/service/MeetingService.java
Labels: ✨ feat, ⚙ build

#9 [#6] 유저 도메인 추가
  src/main/java/findme/dangdangcrew/user/controller/UserController.java
  src/main/java/findme/dangdangcrew/user/dto/UserRequestDto.java
  src/main/java/findme/dangdangcrew/user/dto/UserResponseDto.java
  src/main/java/findme/dangdangcrew/user/entity/User.java
  src/main/java/findme/dangdangcrew/user/repository/UserRepository.java
  src/main/java/findme/dangdangcrew/user/service/UserService.java
Labels: ✨ feat

#10 [#2]알림 도메인 기능 추가, 이벤트 처리 기능 추가
  src/main/java/findme/dangdangcrew/global/entity/BaseTimeEntity.java
  src/main/java/findme/dangdangcrew/global/publisher/EventPublisher.java
  src/main/java/findme/dangdangcrew/global/publisher/SpringEventPublisher.java
  src/main/java/findme/dangdangcrew/notification/controller/EventTestController.java
  src/main/java/findme/dangdangcrew/notification/controller/NotificationController.java
  src/main/java/findme/dangdangcrew/notification/converter/ApplyNotificationConverter.java
  src/main/java/findme/dangdangcrew/notification/converter/HotPlaceNotificationConverter.java
  src/main/java/findme/dangdangcrew/notification/converter/NewMeetingNotificationConverter.java
  src/main/java/findme/dangdangcrew/notification/converter/NotificationConverter.java
  src/main/java/findme/dangdangcrew/notification/converter/NotificationConverterFactory.java
  src/main/java/findme/dangdangcrew/notification/domain/ApplyNotification.java
  src/main/java/findme/dangdangcrew/notification/domain/HotPlaceNotification.java
  src/main/java/findme/dangdangcrew/notification/domain/NewMeetingNotification.java
  src/main/java/findme/dangdangcrew/notification/domain/Notification.java
  src/main/java/findme/dangdangcrew/notification/domain/NotificationEntity.java
  src/main/java/findme/dangdangcrew/notification/domain/NotificationType.java
  src/main/java/findme/dangdangcrew/notification/event/ApplyEvent.java
  src/main/java/findme/dangdangcrew/notification/event/HotPlaceEvent.java
  src/main/java/findme/dangdangcrew/notification/event/NewMeetingEvent.java
  src/main/java/findme/dangdangcrew/notification/event/NotificationEventListener.java
  src/main/java/findme/dangdangcrew/notification/repository/NotificationRepository.java
  src/main/java/findme/dangdangcrew/notification/service/NotificationService.java
Labels: ✨ feat

#19 [#8] 채팅 api 추가
  build.gradle
  src/main/java/findme/dangdangcrew/chat/controller/ChatController.java
  src/main/java/findme/dangdangcrew/chat/dto/ChatMessageRequestDto.java
  src/main/java/findme/dangdangcrew/chat/dto/ChatMessageResponseDto.java
  src/main/java/findme/dangdangcrew/global/config/WebSocketConfig.java
  src/main/resources/application.yml
Labels: ✨ feat, ⚙ build

#16 [#12] 회원가입 API 추가
  build.gradle
  src/main/java/findme/dangdangcrew/global/config/SecurityConfig.java
  src/main/java/findme/dangdangcrew/global/config/SwaggerConfig.java
  src/main/java/findme/dangdangcrew/user/controller/UserController.java
  src/main/java/findme/dangdangcrew/user/dto/UserRequestDto.java
  src/main/java/findme/dangdangcrew/user/repository/UserRepository.java
  src/main/java/findme/dangdangcrew/user/service/UserService.java
Labels: ✨ feat, ⚙ build

#17 [#13] place 도메인 추가
  build.gradle
  src/main/java/findme/dangdangcrew/global/config/WebClientConfig.java
  src/main/java/findme/dangdangcrew/notification/controller/NotificationController.java
  src/main/java/findme/dangdangcrew/notification/event/NewMeetingEvent.java
  src/main/java/findme/dangdangcrew/notification/event/NotificationEventListener.java
  src/main/java/findme/dangdangcrew/place/controller/FavoritePlaceController.java
  src/main/java/findme/dangdangcrew/place/domain/FavoritePlace.java
  src/main/java/findme/dangdangcrew/place/domain/Place.java
  src/main/java/findme/dangdangcrew/place/dto/FavoritePlaceResponseDto.java
  src/main/java/findme/dangdangcrew/place/dto/PlaceRequestDto.java
  src/main/java/findme/dangdangcrew/place/dto/PlaceResponseDto.java
  src/main/java/findme/dangdangcrew/place/repository/FavoritePlaceRepository.java
  src/main/java/findme/dangdangcrew/place/repository/PlaceRepository.java
  src/main/java/findme/dangdangcrew/place/service/FavoritePlaceService.java
  src/main/java/findme/dangdangcrew/place/service/PlaceService.java
  src/main/resources/application.yml
Labels: ✨ feat, ⚙ build

#15 [#11] 평가 도메인 추가
  src/main/java/findme/dangdangcrew/evaluation/controller/EvaluationController.java
  src/main/java/findme/dangdangcrew/evaluation/dto/EvaluationRequestDto.java
  src/main/java/findme/dangdangcrew/evaluation/dto/EvaluationResponseDto.java
  src/main/java/findme/dangdangcrew/evaluation/entity/Evaluation.java
  src/main/java/findme/dangdangcrew/evaluation/repository/EvaluationRepository.java
  src/main/java/findme/dangdangcrew/evaluation/service/EvaluationService.java
  src/main/java/findme/dangdangcrew/user/entity/User.java
  src/main/java/findme/dangdangcrew/user/repository/UserRepository.java
Labels: ✨ feat

#24 [#18] sse 알림 기능 추가
  src/main/java/findme/dangdangcrew/sse/controller/SseController.java
  src/main/java/findme/dangdangcrew/sse/dto/EventPayload.java
  src/main/java/findme/dangdangcrew/sse/infrastructure/ClockHolder.java
  src/main/java/findme/dangdangcrew/sse/infrastructure/SystemClockHolder.java
  src/main/java/findme/dangdangcrew/sse/repository/EmitterRepository.java
  src/main/java/findme/dangdangcrew/sse/repository/SseEmitterRepository.java
  src/main/java/findme/dangdangcrew/sse/service/SseService.java
Labels: ✨ feat

#26 [#20] 채팅방 생성 및 인원 제한 구현
  src/main/java/findme/dangdangcrew/chat/controller/ChatController.java
  src/main/java/findme/dangdangcrew/chat/entity/ChatRoom.java
  src/main/java/findme/dangdangcrew/chat/repository/ChatRoomRepository.java
  src/main/java/findme/dangdangcrew/chat/service/ChatRoomService.java
  src/main/java/findme/dangdangcrew/global/config/SecurityConfig.java
Labels: ✨ feat, 🔨fix

#27 [#23] 이벤트 리스너 클래스 수정
  build.gradle
  src/main/java/findme/dangdangcrew/DangdangcrewApplication.java
  src/main/java/findme/dangdangcrew/global/config/SecurityConfig.java
  src/main/java/findme/dangdangcrew/notification/controller/EventTestController.java
  src/main/java/findme/dangdangcrew/notification/domain/NewMeetingNotification.java
  src/main/java/findme/dangdangcrew/notification/event/HotPlaceEvent.java
  src/main/java/findme/dangdangcrew/notification/event/NewMeetingEvent.java
  src/main/java/findme/dangdangcrew/notification/event/NotificationEventListener.java
  src/main/java/findme/dangdangcrew/notification/service/NotificationService.java
  src/main/java/findme/dangdangcrew/sse/controller/SseController.java
  src/main/java/findme/dangdangcrew/sse/repository/EmitterRepository.java
  src/main/java/findme/dangdangcrew/sse/service/SseService.java
Labels: 🔨fix, 🎨refactor

#31 [#25] 장소-모임 연관관계 매핑
  src/main/java/findme/dangdangcrew/meeting/controller/MeetingController.java
  src/main/java/findme/dangdangcrew/meeting/dto/MeetingRequestDto.java
  src/main/java/findme/dangdangcrew/meeting/entity/Meeting.java
  src/main/java/findme/dangdangcrew/meeting/mapper/MeetingMapper.java
  src/main/java/findme/dangdangcrew/meeting/repository/MeetingRepository.java
  src/main/java/findme/dangdangcrew/meeting/service/MeetingService.java
Labels: ✨ feat

#33 [#30] 토큰 갱신 API 추가
  src/main/java/findme/dangdangcrew/user/controller/UserController.java
  src/main/java/findme/dangdangcrew/user/service/UserService.java
Labels: ✨ feat

#37 [#36] 채팅, 입장, 퇴장 api를 한 개의 api로 통합
  src/main/java/findme/dangdangcrew/chat/controller/ChatController.java
  src/main/java/findme/dangdangcrew/chat/service/ChatRoomService.java
Labels: ✨ feat, 🎨refactor

#44 [#40] logout API
  src/main/java/findme/dangdangcrew/global/config/JwtTokenProvider.java
  src/main/java/findme/dangdangcrew/global/config/SecurityConfig.java
  src/main/java/findme/dangdangcrew/global/config/SwaggerConfig.java
  src/main/java/findme/dangdangcrew/user/controller/UserController.java
  src/main/java/findme/dangdangcrew/user/service/UserService.java
Labels: ✨ feat

#35 [#34] ExceptionHandler 클래스 추가, 공통 ResponseDto 추가
  src/main/java/findme/dangdangcrew/global/dto/ResponseDto.java
  src/main/java/findme/dangdangcrew/global/exception/CustomException.java
  src/main/java/findme/dangdangcrew/global/exception/ErrorCode.java
  src/main/java/findme/dangdangcrew/global/exception/ErrorResponseDto.java
  src/main/java/findme/dangdangcrew/global/exception/GlobalExceptionHandler.java
  src/main/java/findme/dangdangcrew/notification/controller/NotificationController.java
  src/main/java/findme/dangdangcrew/notification/converter/NotificationConverterFactory.java
  src/main/java/findme/dangdangcrew/notification/service/NotificationService.java
  src/main/java/findme/dangdangcrew/place/controller/FavoritePlaceController.java
  src/main/java/findme/dangdangcrew/place/service/FavoritePlaceService.java
  src/main/java/findme/dangdangcrew/place/service/PlaceService.java
  src/main/java/findme/dangdangcrew/user/controller/UserController.java
Labels: ✨ feat, 🎨refactor

#46 [#45] 토큰 추출 공통 로직 리팩토링
  src/main/java/findme/dangdangcrew/global/config/JwtTokenProvider.java
  src/main/java/findme/dangdangcrew/user/controller/UserController.java
Labels: 🎨refactor

#47 [#42] NewMeeting 이벤트 관련 로직 수정
  src/main/java/findme/dangdangcrew/meeting/service/MeetingService.java
  src/main/java/findme/dangdangcrew/notification/controller/EventTestController.java
  src/main/java/findme/dangdangcrew/notification/converter/NewMeetingNotificationConverter.java
  src/main/java/findme/dangdangcrew/notification/domain/NewMeetingNotification.java
  src/main/java/findme/dangdangcrew/notification/event/NewMeetingEvent.java
  src/main/java/findme/dangdangcrew/notification/event/NotificationEventListener.java
  src/main/java/findme/dangdangcrew/place/repository/FavoritePlaceRepository.java
  src/main/java/findme/dangdangcrew/place/service/FavoritePlaceService.java
  src/main/java/findme/dangdangcrew/sse/repository/EmitterRepository.java
  src/main/java/findme/dangdangcrew/sse/repository/SseEmitterRepository.java
  src/main/java/findme/dangdangcrew/sse/service/SseService.java
  src/main/java/findme/dangdangcrew/user/controller/UserController.java
Labels: 🔨fix

#51 [#48] 모임 삭제, 수정 기능 구현
  src/main/java/findme/dangdangcrew/global/exception/ErrorCode.java
  src/main/java/findme/dangdangcrew/meeting/controller/MeetingController.java
  src/main/java/findme/dangdangcrew/meeting/dto/MeetingBasicResponseDto.java
  src/main/java/findme/dangdangcrew/meeting/dto/MeetingDetailResponseDto.java
  src/main/java/findme/dangdangcrew/meeting/entity/Meeting.java
  src/main/java/findme/dangdangcrew/meeting/entity/UserMeeting.java
  src/main/java/findme/dangdangcrew/meeting/entity/enums/MeetingStatus.java
  src/main/java/findme/dangdangcrew/meeting/entity/enums/UserMeetingStatus.java
  src/main/java/findme/dangdangcrew/meeting/mapper/MeetingMapper.java
  src/main/java/findme/dangdangcrew/meeting/repository/MeetingRepository.java
  src/main/java/findme/dangdangcrew/meeting/repository/UserMeetingRepository.java
  src/main/java/findme/dangdangcrew/meeting/service/MeetingService.java
  src/main/java/findme/dangdangcrew/meeting/service/UserMeetingService.java
Labels: ✨ feat

#49 [#41] 토큰 기반 유저 조회 API 추가
  src/main/java/findme/dangdangcrew/user/controller/UserController.java
  src/main/java/findme/dangdangcrew/user/dto/UserResponseDto.java
  src/main/java/findme/dangdangcrew/user/service/UserService.java
Labels: ✨ feat

#56 [#39] 채팅 내역 저장 구현
  build.gradle
  src/main/java/findme/dangdangcrew/chat/controller/ChatController.java
  src/main/java/findme/dangdangcrew/chat/controller/ChatHistoryController.java
  src/main/java/findme/dangdangcrew/chat/entity/ChatMessage.java
  src/main/java/findme/dangdangcrew/chat/repository/ChatMessageRepository.java
  src/main/java/findme/dangdangcrew/chat/service/ChatMessageService.java
  src/main/java/findme/dangdangcrew/chat/service/ChatRoomService.java
  src/main/resources/application.yml
Labels: ✨ feat

#59 [#55] MeetingController에 @Operation 추가
  src/main/java/findme/dangdangcrew/meeting/controller/MeetingController.java
Labels: 🎨refactor

#61 [#43] 핫플레이스 이벤트 발생 로직 추가, redis 관련 로직 리팩토링
  src/main/java/findme/dangdangcrew/DangdangcrewApplication.java
  src/main/java/findme/dangdangcrew/global/config/RedisConfig.java
  src/main/java/findme/dangdangcrew/global/exception/ErrorCode.java
  src/main/java/findme/dangdangcrew/global/service/RedisService.java
  src/main/java/findme/dangdangcrew/meeting/service/MeetingService.java
  src/main/java/findme/dangdangcrew/place/service/HotPlaceService.java
  src/main/java/findme/dangdangcrew/place/service/PlaceService.java
  src/main/java/findme/dangdangcrew/sse/service/SseService.java
  src/main/java/findme/dangdangcrew/user/service/UserService.java
Labels: ✨ feat, 🎨refactor

#62 [#57] jwt filter 설계, 엔티티 반환 메서드 추가
  src/main/java/findme/dangdangcrew/global/config/JwtTokenFilter.java
  src/main/java/findme/dangdangcrew/global/config/JwtTokenProvider.java
  src/main/java/findme/dangdangcrew/global/config/SecurityConfig.java
  src/main/java/findme/dangdangcrew/global/exception/ErrorCode.java
  src/main/java/findme/dangdangcrew/user/controller/UserController.java
  src/main/java/findme/dangdangcrew/user/service/CustomUserDetailsService.java
  src/main/java/findme/dangdangcrew/user/service/UserService.java
Labels: ✨ feat, 🎨refactor

#64 [#58] 중복 입퇴장 불가 구현
  src/main/java/findme/dangdangcrew/chat/controller/ChatController.java
  src/main/java/findme/dangdangcrew/chat/controller/ChatHistoryController.java
  src/main/java/findme/dangdangcrew/chat/entity/ChatParticipant.java
  src/main/java/findme/dangdangcrew/chat/entity/ChatRoom.java
  src/main/java/findme/dangdangcrew/chat/repository/ChatParticipantRepository.java
  src/main/java/findme/dangdangcrew/chat/service/ChatRoomService.java
  src/main/java/findme/dangdangcrew/global/exception/ErrorCode.java
  src/main/java/findme/dangdangcrew/user/service/UserService.java
Labels: ✨ feat

#66 [#53] 모임 도메인에서 User 정보 가져오는 부분 수정
  src/main/java/findme/dangdangcrew/global/exception/ErrorCode.java
  src/main/java/findme/dangdangcrew/meeting/controller/MeetingController.java
  src/main/java/findme/dangdangcrew/meeting/service/MeetingService.java
  src/main/java/findme/dangdangcrew/meeting/service/UserMeetingService.java
Labels: 🎨refactor

#72 [#68] 모임 참가 취소시 평가점수 감소 구현
  src/main/java/findme/dangdangcrew/meeting/controller/MeetingController.java
  src/main/java/findme/dangdangcrew/meeting/service/MeetingService.java
  src/main/java/findme/dangdangcrew/meeting/service/UserMeetingService.java
  src/main/java/findme/dangdangcrew/user/entity/User.java
Labels: ✨ feat, 🔨fix, 🎨refactor

#73 [#63] notification, sse, place 도메인 리팩토링
  src/main/java/findme/dangdangcrew/global/exception/ErrorCode.java
  src/main/java/findme/dangdangcrew/notification/controller/EventTestController.java
  src/main/java/findme/dangdangcrew/notification/controller/NotificationController.java
  src/main/java/findme/dangdangcrew/notification/converter/ApplyNotificationConverter.java
  src/main/java/findme/dangdangcrew/notification/converter/HotPlaceNotificationConverter.java
  src/main/java/findme/dangdangcrew/notification/converter/NewMeetingNotificationConverter.java
  src/main/java/findme/dangdangcrew/notification/domain/ApplyNotification.java
  src/main/java/findme/dangdangcrew/notification/service/NotificationService.java
  src/main/java/findme/dangdangcrew/place/controller/FavoritePlaceController.java
  src/main/java/findme/dangdangcrew/place/dto/PlaceResponseDto.java
  src/main/java/findme/dangdangcrew/place/service/FavoritePlaceService.java
  src/main/java/findme/dangdangcrew/place/service/HotPlaceService.java
  src/main/java/findme/dangdangcrew/sse/controller/SseController.java
  src/main/java/findme/dangdangcrew/sse/dto/EventPayload.java
  src/main/java/findme/dangdangcrew/sse/repository/EmitterRepository.java
  src/main/java/findme/dangdangcrew/sse/repository/SseEmitterRepository.java
  src/main/java/findme/dangdangcrew/sse/service/SseService.java
  src/main/resources/application.yml
Labels: 🔨fix, 🎨refactor

#75 [#71] CustomException으로 예외 처리 수정
  src/main/java/findme/dangdangcrew/global/exception/ErrorCode.java
  src/main/java/findme/dangdangcrew/user/service/UserService.java
Labels: 🎨refactor

#76 [#69] 모임 상태 변경
  src/main/java/findme/dangdangcrew/meeting/repository/MeetingRepository.java
  src/main/java/findme/dangdangcrew/meeting/service/MeetingService.java
  src/main/java/findme/dangdangcrew/meeting/service/UserMeetingService.java
Labels: ✨ feat, 🎨refactor

#78 [#74] LeaderAction 알림 기능 추가
  src/main/java/findme/dangdangcrew/global/exception/ErrorCode.java
  src/main/java/findme/dangdangcrew/meeting/dto/MeetingApplicationUpdateRequestDto.java
  src/main/java/findme/dangdangcrew/meeting/service/MeetingService.java
  src/main/java/findme/dangdangcrew/notification/converter/ApplyNotificationConverter.java
  src/main/java/findme/dangdangcrew/notification/converter/LeaderActionNotificationConverter.java
  src/main/java/findme/dangdangcrew/notification/converter/NotificationConverterFactory.java
  src/main/java/findme/dangdangcrew/notification/domain/LeaderActionNotification.java
  src/main/java/findme/dangdangcrew/notification/domain/NotificationEntity.java
  src/main/java/findme/dangdangcrew/notification/domain/NotificationType.java
  src/main/java/findme/dangdangcrew/notification/event/LeaderActionEvent.java
  src/main/java/findme/dangdangcrew/notification/event/LeaderActionType.java
  src/main/java/findme/dangdangcrew/notification/event/NotificationEventListener.java
  src/main/java/findme/dangdangcrew/sse/service/SseService.java
Labels: ✨ feat

#84 [#81] 모임 관련 수정사항
  src/main/java/findme/dangdangcrew/global/exception/ErrorCode.java
  src/main/java/findme/dangdangcrew/meeting/controller/MeetingController.java
  src/main/java/findme/dangdangcrew/meeting/controller/MeetingLeaderController.java
  src/main/java/findme/dangdangcrew/meeting/dto/MeetingBasicResponseDto.java
  src/main/java/findme/dangdangcrew/meeting/dto/MeetingUserResponseDto.java
  src/main/java/findme/dangdangcrew/meeting/dto/MeetingUserStatusUpdateRequestDto.java
  src/main/java/findme/dangdangcrew/meeting/entity/enums/MeetingStatus.java
  src/main/java/findme/dangdangcrew/meeting/entity/enums/UserMeetingStatus.java
  src/main/java/findme/dangdangcrew/meeting/mapper/MeetingMapper.java
  src/main/java/findme/dangdangcrew/meeting/repository/MeetingRepository.java
  src/main/java/findme/dangdangcrew/meeting/repository/UserMeetingRepository.java
  src/main/java/findme/dangdangcrew/meeting/service/MeetingLeaderService.java
  src/main/java/findme/dangdangcrew/meeting/service/MeetingService.java
  src/main/java/findme/dangdangcrew/meeting/service/MeetingUserService.java
  src/main/java/findme/dangdangcrew/meeting/service/UserMeetingService.java
Labels: ✨ feat, 🔨fix, 🎨refactor

#82 [#65] 토큰에서 user 정보 추출 로직 반영해서 리팩토링
  src/main/java/findme/dangdangcrew/chat/controller/ChatController.java
  src/main/java/findme/dangdangcrew/chat/dto/ChatMessageRequestDto.java
  src/main/java/findme/dangdangcrew/chat/dto/ChatMessageResponseDto.java
  src/main/java/findme/dangdangcrew/chat/service/ChatMessageService.java
  src/main/java/findme/dangdangcrew/chat/service/ChatRoomService.java
  src/main/java/findme/dangdangcrew/global/config/WebSocketConfig.java
  src/main/java/findme/dangdangcrew/global/exception/ErrorCode.java
  src/main/java/findme/dangdangcrew/global/interceptor/JwtChannelInterceptor.java
Labels: ✨ feat, 🎨refactor

#83 [#80] 알림, 즐겨찾기 페이징 조회 리팩토링
  src/main/java/findme/dangdangcrew/global/dto/PagingResponseDto.java
  src/main/java/findme/dangdangcrew/notification/controller/NotificationController.java
  src/main/java/findme/dangdangcrew/notification/converter/NewMeetingNotificationConverter.java
  src/main/java/findme/dangdangcrew/notification/repository/NotificationRepository.java
  src/main/java/findme/dangdangcrew/notification/service/NotificationService.java
  src/main/java/findme/dangdangcrew/place/controller/FavoritePlaceController.java
  src/main/java/findme/dangdangcrew/place/domain/FavoritePlace.java
  src/main/java/findme/dangdangcrew/place/dto/FavoritePlaceResponseDto.java
  src/main/java/findme/dangdangcrew/place/repository/FavoritePlaceRepository.java
  src/main/java/findme/dangdangcrew/place/service/FavoritePlaceService.java
Labels: 🎨refactor

#85 [#60] 작성한 평가 조회, dto 반영
  src/main/java/findme/dangdangcrew/evaluation/controller/EvaluationController.java
  src/main/java/findme/dangdangcrew/evaluation/dto/EvaluationCreateResponseDto.java
  src/main/java/findme/dangdangcrew/evaluation/dto/EvaluationResponseDto.java
  src/main/java/findme/dangdangcrew/evaluation/dto/ReceivedEvaluationsResponseDto.java
  src/main/java/findme/dangdangcrew/evaluation/dto/WrittenEvaluationsResponseDto.java
  src/main/java/findme/dangdangcrew/evaluation/repository/EvaluationRepository.java
  src/main/java/findme/dangdangcrew/evaluation/service/EvaluationService.java
  src/main/java/findme/dangdangcrew/global/exception/ErrorCode.java
Labels: ✨ feat, 🎨refactor

#87 [#79] 서비스, 이벤트 핸들러 테스트 코드 추가
  build.gradle
  src/main/resources/application.yml
  src/test/java/findme/dangdangcrew/global/service/RedisServiceTest.java
  src/test/java/findme/dangdangcrew/notification/controller/NotificationControllerTest.java
  src/test/java/findme/dangdangcrew/notification/event/NotificationEventListenerTest.java
  src/test/java/findme/dangdangcrew/notification/service/NotificationServiceTest.java
  src/test/java/findme/dangdangcrew/place/service/FavoritePlaceServiceTest.java
  src/test/java/findme/dangdangcrew/place/service/HotPlaceServiceTest.java
  src/test/java/findme/dangdangcrew/place/service/PlaceServiceTest.java
  src/test/java/findme/dangdangcrew/sse/service/SseServiceTest.java
Labels: 💡test

#90 [#77] 유저 테스트
  build.gradle
  src/main/java/findme/dangdangcrew/user/dto/ChangePasswordRequestDto.java
  src/main/java/findme/dangdangcrew/user/dto/LoginRequestDto.java
  src/main/java/findme/dangdangcrew/user/dto/TokenRefreshRequestDto.java
  src/main/java/findme/dangdangcrew/user/dto/TokenResponseDto.java
  src/main/java/findme/dangdangcrew/user/dto/UserRequestDto.java
  src/main/java/findme/dangdangcrew/user/dto/UserResponseDto.java
  src/test/java/findme/dangdangcrew/user/controller/UserControllerIntegrationTest.java
  src/test/java/findme/dangdangcrew/user/controller/UserControllerTest.java
  src/test/java/findme/dangdangcrew/user/service/UserServiceTest.java
  src/test/resources/application-test.yml
  src/test/resources/schema.sql
Labels: 💡test, ⚙ build

#89 [#54] 모임 테스트코드 작성
  src/test/java/findme/dangdangcrew/meeting/MeetingTestData.java
  src/test/java/findme/dangdangcrew/meeting/controller/MeetingControllerIntegrationTest.java
  src/test/java/findme/dangdangcrew/meeting/controller/MeetingLeaderControllerIntegrationTest.java
  src/test/java/findme/dangdangcrew/meeting/service/MeetingLeaderServiceTest.java
  src/test/java/findme/dangdangcrew/meeting/service/MeetingServiceTest.java
  src/test/java/findme/dangdangcrew/meeting/service/MeetingUserServiceTest.java
Labels: 💡test

#93 [#86] 채팅 도메인 관련 테스트 코드 작성
  src/test/java/findme/dangdangcrew/chat/controller/ChatControllerWebSocketTest.java
  src/test/java/findme/dangdangcrew/chat/controller/ChatHistoryControllerTest.java
  src/test/java/findme/dangdangcrew/chat/controller/ChatIntegrationTest.java
  src/test/java/findme/dangdangcrew/chat/service/ChatMessageServiceTest.java
  src/test/java/findme/dangdangcrew/chat/service/ChatRoomServiceTest.java
Labels: 💡test

#94 [#52] 평가 테스트 코드 작성
  src/main/java/findme/dangdangcrew/evaluation/controller/EvaluationController.java
  src/main/java/findme/dangdangcrew/evaluation/dto/EvaluationRequestDto.java
  src/test/java/findme/dangdangcrew/evaluation/controller/EvaluationControllerTest.java
  src/test/java/findme/dangdangcrew/evaluation/service/EvaluationServiceTest.java
Labels: 💡test

#98 fix: WebSocketConfig 수정
  src/main/java/findme/dangdangcrew/global/config/WebSocketConfig.java
Labels: 🔨fix

#100 [#99] swagger 태그 및 설명 통일
  src/main/java/findme/dangdangcrew/evaluation/controller/EvaluationController.java
  src/main/java/findme/dangdangcrew/notification/controller/NotificationController.java
  src/main/java/findme/dangdangcrew/place/controller/FavoritePlaceController.java
  src/main/java/findme/dangdangcrew/sse/controller/SseController.java
  src/main/java/findme/dangdangcrew/user/controller/UserController.java
Labels: 📘 docs
